# .forge-lock.hcl — DO NOT EDIT MANUALLY
# Generated by forge. Changes will be overwritten on sync.

blueprint {
  registry_url = "/Users/donaldgifford/code/forge-registry"
  name         = "homelab-go"
  path         = "homelab/go"
}

created_at    = "2026-06-01T02:41:04.337794Z"
last_synced   = "2026-06-01T02:41:04.337794Z"
forge_version = "0.7.0"

variables {
  git_host               = "github.com"
  git_provider           = "github"
  go_version             = "1.26.3"
  license                = "Apache-2.0"
  project_description    = "HCL2 Shared library"
  project_name           = "hclkit"
  project_org            = "donaldgifford"
  renovate_config_prefix = "github"
}

default ".checkmake.ini" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:123f1dc4a0f6e608cd57546d72894791ef719ad07cc0fdd53016d57557cb9284"
}

default ".claude/settings.json" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:7fa2145b3bc9a192465144e24e2179d6062debdc730ea5012ef11a73982b2eb7"
}

default ".docz.yaml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:f3fb2387d31e3b07fa2a1efdf3e974814b13113c763a7b82d7425eb2967bbcfc"
}

default ".github/labeler.yml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:d249f58945cdffbb34b9cf9a50e12e82394e09413d14657771d8e3fe4408b81f"
}

default ".github/workflows/pr-labels.yml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:9d0bbe7ec5e56ac192a21ed557d5dc700375c60b555a874bc22c05eb57bd86d4"
}

default ".makefmt.yml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:c56b8f4be0b7722a0e8fda97faf4d8c29e4ff75193acf663bf5a5b0e7fbf4808"
}

default ".markdownlint.yaml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:dc9182bd0b399616bd2b6933eb4b2a756674cedb43dbea914cf61f9180e3fc92"
}

default ".prettierrc.yaml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:402823be7f1d14a6bdd7a8801c6392f7b8e74675e842aa355fccc07766b538d8"
}

default ".yamlfmt.yml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:d214a4f56043cad5e01bd70e3530155df3bf7372bd2571aba87bcee0c1dcca73"
}

default ".yamllint.yml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:3f8575b37ea4a59395110326535d36573208fc6495ac47e357512fa7b8bbf7a9"
}

default ".env.example.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:0ce3a32ff5e23814462c5c5c37428fa690f85b4b234f4228c46ba5b12e9680de"
}

default ".github/workflows/labels-sync.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:b8b734d04c4bcbaa9df6bda67569d1d260bcac61446df029484ef0bb0ae0a5ef"
}

default ".github/workflows/lint.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:c6436894547134b34a05b957597e6955a0ec3f2080ae3d4c7923d6cc97dadde6"
}

default ".github/workflows/trufflehog.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:7aba0b644b151b40e2a8e20ae2267bb3f900ccb030d6d0f16664eeacbf317101"
}

default "catalog-info.yaml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:d2b8e65e27ef03a94cd76b17201a640e64e387c132d0f13086f8dc7a5db63d98"
}

default "docs/index.md.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:6cfe816593f0d2669dcda82a366ddb43741c4d7fafffc7cedc728a0c5ab6bd38"
}

default "labels.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:7030a2ff9efddd475aed845b1b0125dc538b420d0a899b29700462000b4cc77b"
}

default "mise.toml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:4a4179fda1bdc0c79dd15240201cbb8ddc1a070eb21cf09d75a0c39824260660"
}

default "mkdocs.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:5da351c8cf980f91f2781df068754db9e04731edd3d66cc77e3b806916233ee0"
}

default "renovate.json5.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:8f054bc1b1ccbd32bb561ff0e7aeba9a6851531848d7c1a159cf1fd404130cc9"
}
