docs_dir: docs
markdown_extensions:
    - admonition
    - tables
    - toc:
        permalink: true
nav:
    - Home: index.md
    - ADRs:
        - Overview: adr/README.md
    - Design:
        - Overview: design/README.md
        - 'DESIGN-0001: hclkit v0 library and validator binary': design/0001-hclkit-v0-library-and-validator-binary.md
    - Implementation Plans:
        - Overview: impl/README.md
    - Investigations:
        - Overview: investigation/README.md
        - 'INV-0001: HCL Config Reuse: Shared Library vs Full DSL': investigation/0001-hcl-config-reuse-shared-library-vs-full-dsl.md
    - Plans:
        - Overview: plan/README.md
    - RFCs:
        - Overview: rfc/README.md
        - 'RFC-0001: Build hclkit as a mechanism-only HCL library': rfc/0001-build-hclkit-as-a-mechanism-only-hcl-library.md
plugins:
    - techdocs-core
site_description: HCL2 Shared library
site_name: hclkit
